// consts
export const SWIZZLES = ['x', 'y', 'z', 'w', 'r', 'g', 'b', 'a', 's', 't', 'p', 'q'] as const

export const NODE_TYPES = [
        'float',
        'int',
        'uint',
        'bool',
        'color',
        'vec2',
        'vec3',
        'vec4',
        'mat2',
        'mat3',
        'mat4',
        'ivec2',
        'ivec3',
        'ivec4',
        'uvec2',
        'uvec3',
        'uvec4',
        'bvec2',
        'bvec3',
        'bvec4',
] as const

export const OPERATORS = {
        add: '+',
        sub: '-',
        mul: '*',
        div: '/',
        mod: '%',
        equal: '==',
        notEqual: '!=',
        lessThan: '<',
        lessThanEqual: '<=',
        greaterThan: '>',
        greaterThanEqual: '>=',
        and: '&&',
        or: '||',
        bitAnd: '&',
        bitOr: '|',
        bitXor: '^',
        shiftLeft: '<<',
        shiftRight: '>>',
} as const

export const OPERATOR_KEYS = Object.keys(OPERATORS)

export const FUNCTIONS = [
        'abs',
        'acos',
        'asin',
        'atan',
        'atan2',
        'ceil',
        'clamp',
        'cos',
        'cross',
        'degrees',
        'distance',
        'dot',
        'exp',
        'exp2',
        'faceforward',
        'floor',
        'fract',
        'length',
        'all',
        'any',
        'bitcast',
        'cbrt',
        'dFdx',
        'dFdy',
        'difference',
        'equals',
        'fwidth',
        'inverseSqrt',
        'lengthSq',
        'log',
        'log2',
        'max',
        'min',
        'mix',
        'negate',
        'normalize',
        'oneMinus',
        'pow',
        'pow2',
        'pow3',
        'pow4',
        'radians',
        'reciprocal',
        'reflect',
        'refract',
        'round',
        'saturate',
        'sign',
        'sin',
        'smoothstep',
        'sqrt',
        'step',
        'tan',
        'transformDirection',
        'trunc',
] as const
