export const SWIZZLES = ['x', 'y', 'z', 'w', 'r', 'g', 'b', 'a', 's', 't', 'p', 'q'] as const

export const CONSTANTS = [
        'float',
        'int',
        'uint',
        'bool',
        'color',
        'vec2',
        'vec3',
        'vec4',
        'mat2',
        'mat3',
        'mat4',
        'ivec2',
        'ivec3',
        'ivec4',
        'uvec2',
        'uvec3',
        'uvec4',
        'bvec2',
        'bvec3',
        'bvec4',
] as const

export const CONVERSIONS = [
        'toFloat',
        'toInt',
        'toUint',
        'toBool',
        'toVec2',
        'toVec3',
        'toVec4',
        'toIvec2',
        'toIvec3',
        'toIvec4',
        'toUvec2',
        'toUvec3',
        'toUvec4',
        'toBvec2',
        'toBvec3',
        'toBvec4',
        'toMat2',
        'toMat3',
        'toMat4',
        'toColor',
] as const

export const OPERATORS = {
        add: '+',
        sub: '-',
        mul: '*',
        div: '/',
        mod: '%',
        equal: '==',
        notEqual: '!=',
        lessThan: '<',
        lessThanEqual: '<=',
        greaterThan: '>',
        greaterThanEqual: '>=',
        and: '&&',
        or: '||',
        bitAnd: '&',
        bitOr: '|',
        bitXor: '^',
        shiftLeft: '<<',
        shiftRight: '>>',
} as const

export const OPERATOR_KEYS = Object.keys(OPERATORS) as (keyof typeof OPERATORS)[]

export const FUNCTIONS = [
        'abs',
        'acos',
        'asin',
        'atan',
        'atan2',
        'ceil',
        'clamp',
        'cos',
        'cross',
        'degrees',
        'distance',
        'dot',
        'exp',
        'exp2',
        'faceforward',
        'floor',
        'fract',
        'length',
        'all',
        'any',
        'bitcast',
        'cbrt',
        'dFdx',
        'dFdy',
        'difference',
        'equals',
        'fwidth',
        'inverseSqrt',
        'lengthSq',
        'log',
        'log2',
        'max',
        'min',
        'mix',
        'negate',
        'normalize',
        'oneMinus',
        'pow',
        'pow2',
        'pow3',
        'pow4',
        'radians',
        'reciprocal',
        'reflect',
        'refract',
        'round',
        'saturate',
        'sign',
        'sin',
        'smoothstep',
        'sqrt',
        'step',
        'tan',
        'transformDirection',
        'trunc',
        // Texture functions
        'texture',
        'cubeTexture',
        'textureSize',
] as const

export const TYPE_MAPPING = {
        float: 'f32',
        int: 'i32',
        uint: 'u32',
        bool: 'bool',
        vec2: 'vec2f',
        vec3: 'vec3f',
        vec4: 'vec4f',
        mat2: 'mat2x2f',
        mat3: 'mat3x3f',
        mat4: 'mat4x4f',
        ivec2: 'vec2i',
        ivec3: 'vec3i',
        ivec4: 'vec4i',
        uvec2: 'vec2u',
        uvec3: 'vec3u',
        uvec4: 'vec4u',
        bvec2: 'vec2<bool>',
        bvec3: 'vec3<bool>',
        bvec4: 'vec4<bool>',
} as const
